"""update_chat_messages

Revision ID: 817cead9a490
Revises: af2d1140c5f4
Create Date: 2026-08-22 20:14:12.146325
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '817cead9a490'
down_revision: Union[str, None] = 'af2d1140c5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('message_type', sa.String(length=50), nullable=False))
    op.add_column('chat_messages', sa.Column('meeting_id', sa.UUID(), nullable=True))
    op.add_column('chat_messages', sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_meeting_id'), 'chat_messages', ['meeting_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_meeting_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('chat_messages', 'metadata_')
    op.drop_column('chat_messages', 'meeting_id')
    op.drop_column('chat_messages', 'message_type')
    # ### end Alembic commands ###
